# Generated by Django 4.2.5 on 2023-09-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodos',
            name='periodo',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='periodo',
            field=models.CharField(max_length=50),
        ),
    ]
