# Generated by Django 4.2.5 on 2023-09-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cursos_area_saber_cursos_instituicao_matriculas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='carga_horaria_total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursos',
            name='duracao_meses',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
